steps:
  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=http://35.189.253.12'
    - '-Dsonar.login=admin'
    - 'Dsonar.password=admin'
    - '-Dsonar.projectKey=golang-example'
    - '-Dsonar.sources=.'
